pipeline {
    agent any
    environment {
        ORACLE_USER = 'amit'
        ORACLE_PASS = 'texas'
        ORACLE_DSN  = 'localhost:1521/XEPDB1'
    }
    stages {
        stage('Clone Repo') {
            steps {
				git branch: 'main', url: 'https://github.com/amitms/healthcare_dw.git'
            }
			
        }
		stage('Check Python') {
			steps {
				bat 'python --version'
				bat 'python -m pip --version'
				bat 'python -m pip list'
			}
		}

        stage('Install Dependencies') {
            steps {
                bat '''
                REM Upgrade pip, setuptools, wheel first
				"C:\\Program Files\\Python314\\python.exe" -m ensurepip --upgrade
				"C:\\Program Files\\Python314\\python.exe" -m pip install --upgrade pip setuptools wheel

                REM Then install other dependencies including cx_Oracle
                "C:\\Program Files\\Python314\\python.exe" -m pip install pandas sqlalchemy cx_Oracle apache-airflow
                '''
            }
        }
		
        stage('Optional PL/SQL Table Creation') {
            steps {
                sh '''
                sqlplus $ORACLE_USER/$ORACLE_PASS@$ORACLE_DSN @sql/01_create_oltp_tables.sql
                sqlplus $ORACLE_USER/$ORACLE_PASS@$ORACLE_DSN @sql/02_create_staging_tables.sql
                sqlplus $ORACLE_USER/$ORACLE_PASS@$ORACLE_DSN @sql/03_create_dimensional_tables.sql
                '''
            }
        }

        stage('Load Staging via Python ETL') {
            steps {
                sh 'python3 etl/load_staging.py'
            }
        }

        stage('Run PL/SQL ETL Procedures') {
			steps {
                sh '''
				sqlplus $ORACLE_USER/$ORACLE_PASS@$ORACLE_DSN @etl/run_etl_pipeline.sql
                '''
            }
        }

        stage('Verify Load') {
            steps {
                echo 'ETL pipeline completed successfully'
            }
        }
    }
}