pipeline {
    agent any
    environment {
        ORACLE_USER = 'amit'
        ORACLE_PASS = 'texas'
        ORACLE_DSN  = 'localhost:1521/XEPDB1'
        
        PYTHON_EXE = 'C:\\Program Files\\Python314\\python.exe'
        ORACLE_INSTANT_CLIENT = 'C:\\oracle\\instantclient_23_0'
    }
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/amitms/healthcare_dw.git'
            }
        }

        stage('Set Oracle Path') {
            steps {
                bat """
                REM Add Oracle Instant Client to PATH
                set PATH=%ORACLE_INSTANT_CLIENT%;%PATH%
                """
            }
        }

        stage('Install Python Dependencies') {
            steps {
                bat """
                REM Upgrade pip, setuptools, wheel
                "%PYTHON_EXE%" -m ensurepip --upgrade
                "%PYTHON_EXE%" -m pip install --upgrade pip setuptools wheel

                REM Install other dependencies
				"%PYTHON_EXE%" -m pip install oracledb
				REM "%PYTHON_EXE%" -m pip install --no-build-isolation cx_Oracle
                "%PYTHON_EXE%" -m pip install oracledb pandas 
                REM "%PYTHON_EXE%" -m pip install apache-airflow
				"%PYTHON_EXE%" -m pip install --force-reinstall SQLAlchemy==2.0.48 --no-deps
                """
            }
        }

        stage('Check Python & pkg_resources') {
            steps {
                bat """
                "%PYTHON_EXE%" --version
                "%PYTHON_EXE%" -m pip --version
                "%PYTHON_EXE%" -m pip list
                REM "%PYTHON_EXE%" -c "import pkg_resources; print('pkg_resources version:', pkg_resources.__version__)"
				"%PYTHON_EXE%" -c "import oracledb; print('oracledb version:', oracledb.__version__)"
				"%PYTHON_EXE%" -c "import sqlalchemy; print('sqlalchemy version:', sqlalchemy.__version__)"
                """
            }
        }

        stage('Optional PL/SQL Table Creation') {
            steps {
                bat """
                sqlplus %ORACLE_USER%/%ORACLE_PASS%@%ORACLE_DSN% @sql\\01_create_oltp_tables.sql
                sqlplus %ORACLE_USER%/%ORACLE_PASS%@%ORACLE_DSN% @sql\\02_create_staging_tables.sql
                sqlplus %ORACLE_USER%/%ORACLE_PASS%@%ORACLE_DSN% @sql\\04_create_dimensional_tables.sql
                """
            }
        }
		
        stage('Load Staging via Python ETL') {
            steps {
                bat "\"%PYTHON_EXE%\" scripts\\load_staging.py"
            }
        }

        stage('Transformation') {
            steps {
                bat """
                sqlplus %ORACLE_USER%/%ORACLE_PASS%@%ORACLE_DSN% @sql\\03_transfrom_tables.sql              
                """
            }
        }

        stage('DW loading') {
            steps {
                bat "sqlplus %ORACLE_USER%/%ORACLE_PASS%@%ORACLE_DSN% @etl\\run_etl_pipeline.sql"
            }
        }

        stage('Verify Load') {
            steps {
                echo 'ETL pipeline completed successfully'
            }
        }
    }
}