-- Dimensions
CREATE TABLE Dim_Patient (
    patient_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR2(50),
    age NUMBER,
    gender VARCHAR2(10)
);

CREATE TABLE Dim_Doctor (
    doctor_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id VARCHAR2(50),
    specialization VARCHAR2(100)
);

CREATE TABLE Dim_Date (
    date_key NUMBER PRIMARY KEY,
    the_date DATE,
    month NUMBER,
    year NUMBER
);

--Fact Table
CREATE TABLE Fact_Visits (
    visit_key NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_key NUMBER,
    doctor_key NUMBER,
    date_key NUMBER,
    total_cost NUMBER(10,2)
);